config/routes.rb
Rails.application.routes.draw do
  resources :user
  #resources :valuation
  get 'valuation/index'
  get 'valuation/indexView'
  resources :valuation
  
  
  get 'top/main'
  post 'top/login'
  get 'top/logout'
  root 'user#index'
  get 'user/show'
  
  resources :management
  get 'management/index'
  get 'management/new'
  
  get 'valuationviews/show'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/management.rb
class Management < ApplicationRecord
    has_many :valuation
end

app/models/user.rb
class User < ApplicationRecord
    #TODO: validates
    has_many :valuation #, dependent: :destroy
    
    validates :password, presence: true, confirmation: true, length: { maximum: 8 }
    validates :student_num, uniqueness: true, presence: true, length: { is: 10 },  format: { with: /[0-9]{2}+1114+[0-9]{4}/ }
    attr_accessor :password, :password_confirmation

  def password=(val)
    if val.present?
      self.pass = BCrypt::Password.create(val)
    end
    @password = val
  end
end

app/models/valuation.rb
class Valuation < ApplicationRecord
    validates :comment, presence: true ,length: { maximum: 300 }
    validates :star, presence: true ,numericality: { less_than: 101 ,greater_than: -1 }
    belongs_to :user
    #belongs_to :management
end

app/models/valuationview.rb
class Valuationview < ApplicationRecord
    has_many :valuation
    belongs_to :management
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
        def current_user
            if session[:login_student_num]
                User.find_by(student_num: session[:login_student_num])
            end
        end
    helper_method :current_user
end

app/controllers/management_controller.rb
class ManagementController < ApplicationController
    def index
        @management = Management.all
        @user = User.all
        logger.debug @management
    end
    def new
        @management = Management.new
    end
    
    def create
        logger.debug "---------------"
        @management = Management.new(subject: params[:management][:subject],
        annual: params[:management][:annual], link: params[:management][:link])
        if @management.valid?
          flash[:notice] = 'データ登録完了'
          @management.save
          redirect_to management_index_path
        else
          render 'new'
        end
    end
    def destroy
        management = Management.find(params[:id])
        if management.destroy
          flash[:notice] = 'データを削除しました'
        end
        redirect_to management_index_path
    end
    
    def show
        @management = Management.find(params[:id])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        render 'login'
    end

  def login
    user = User.find_by(student_num: params[:student_num])
    if user and BCrypt::Password.new(user.pass) == params[:pass]
      flash[:notice] = 'ログイン成功'
      session[:login_student_num] = user.student_num #[:login_uid]
      redirect_to root_path
    else
      flash[:notice] = 'ログイン失敗'
      render 'login'
    end
  end

  def logout
    flash[:notice] = 'ログアウトに成功'
    session.delete(:login_student_num)
    
    redirect_to root_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def index
        @user = User.all
    end
    def mypage
        @user = User.all
    end
    def new
        @user = User.new
    end
    
    def create
        logger.debug "---------------"
        @user = User.new(student_num: params[:user][:student_num],
        password: params[:user][:password],
        password_confirmation: params[:user][:password_confirmation])
        if @user.valid?
          flash[:notice] = 'ユーザ登録完了'
          @user.pass = BCrypt::Password.create(params[:user][:password])
          @user.save
          redirect_to root_path
        else
          render 'new'
        end
    end
    def destroy
        user = User.find(params[:id])
        if user.destroy
          flash[:notice] = 'ユーザを削除しました'
        end
        redirect_to root_path
    end
    
end

app/controllers/valuation_controller.rb
class ValuationController < ApplicationController
    def index
        @valuation = Valuation.all
        @management = Management.all
        if params[:search] == nil or params[:search] == ''
          @management = Management.all
        else
          @management = Management.where("subject LIKE ? ",'%' + params[:search] + '%') + Management.where("annual LIKE ? ",'%' + params[:search] + '%') 
        end
    end
    def indexView
        @valuation = Valuation.all
        @management = Management.all
    end
    def new
        @management = Management.all
        @management = Management.find(params[:id])
        @valuation = Valuation.new
    end
    
    def create
        user = User.find_by(student_num: current_user.student_num)
        #management = Management.find[:id](params[:id])
        logger.debug params
        @valuation = Valuation.new(comment: params[:valuation][:comment], star: params[:valuation][:star],
                                    user_id: user.id, tdate: Time.current, subject: params[:id])
        logger.debug "--------"
        if @valuation.save
          #TODO: ツイートが成功したことをユーザに知らせる
          flash[:notice] = '評価登録完了！'
          redirect_to valuation_index_path
        else
          render 'new'
        end
    end
end

app/controllers/valuationviews_controller.rb
class ValuationviewsController < ApplicationController
    def show
        @management = Management.all
        @management = Management.find(params[:id])
        @valuation = Valuation.where(subject: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/management_helper.rb
module ManagementHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/valuation_helper.rb
module ValuationHelper
end

app/helpers/valuationviews_helper.rb
module ValuationviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentCourse</title>
    <%= favicon_link_tag 'icon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </head>
  
  <body>
    <%= yield %>
    
  </body>
  <footer>
    <div class="container">
      <div class="box">
          <p>
            <% if current_user %>
              ログイン中（<%= current_user.student_num %>さん）<br>
            <% else %>
              ログインしていません
            <% end %>
          </p>
          <p>&copy; Kanbara&Ogita</p>
      </div>
    </div>
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg"><path id="wave" d=""/></svg>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.1/TweenMax.min.js"></script>
    <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/85188/jquery.wavify.js"></script>
  </footer>
</html>

<style>
svg {
  height: 25vw;
  width: 100vw;
  position: absolute;
  top: 1000px;
  left: 0;
}
.container {
  margin-top:200px;
  justify-content: center;
  align-items: center;
  height: 100vh;
}
.box {
  text-align: center;
  text-align: center;
  z-index: 1;
  position: absolute;
  top:1250px;
  left:800px;
}

</style>
<script>
$('#wave').wavify({
  height: 60,
  bones: 3,
  amplitude: 40,
  color: '#1b9bff',
  speed: .25
});
</script>

app/views/management/index.html.erb
<html>
<header>
  <nav>
    <ul>
    <li class="current"><%= link_to 'ホーム', root_path %></li>
    <li><% if current_user %>
          <%= link_to 'ログアウト', top_logout_path %>
        <% else %>
          <%= link_to 'ログイン', top_main_path %>
        <% end %></li>
    <li><% if current_user %>
          <%= current_user.student_num.to_s + "さん" %>
        <% else %>
          ゲストさん
        <% end %></li>
    </ul>
  </nav>
</header>
  <body>
    <div class="main">
      <div class = "main1">
        <h1>管理者画面</h1>
      <% if flash[:notice] %>
        <%= flash[:notice] %>
      <% end %>
      <h2>科目登録</h2>
      <button><%= link_to '新規科目の追加', management_new_path %></button>
      <button><%= link_to '戻る', root_path %></button>
      
      <table border="1">
          <tr>
            <th>　科目名　</th>
            <th>　開講年次　</th>
            <th>　シラバス　</th>
            <th>　データの削除　</th>
          </tr>
          <% @management.each do |e| %>
          <tr>
            <td><%= e.subject %></td>
            <td><%= e.annual %></td>
            <td><%= link_to 'シラバス', e.link, target: :_blank %></td>
            <td><%= link_to '削除', management_path(e), method: :delete %></td>
          </tr>
          <% end %>
      </table>
      </div>
      <br>
      <div class = "main2">
        <h2>ユーザ管理一覧</h2>
      <button><%= link_to '新規ユーザの追加', new_user_path %></button>
      <button><%= link_to '戻る', root_path %></button>
      <table border="1">
        <tr>
          <th>　学籍番号　</th>
          <th>　パスワード　</th>
          <th>　ユーザの削除　</th>
        </tr>
      <% @user.each do |e| %>
          <tr>
            <td><%= e.student_num %></td>
            <td><%= e.pass %></td>
            <td><%= link_to '削除', user_path(e), method: :delete %></td>
          </p>
      <% end %>
      </table>
      </div>
    </div>
  </body>
</html>
<style>
nav{
border-bottom: 1px solid #000000;
}
nav ul{
display: table;
margin: 0 auto;
padding: 0;
width: 80%;
text-align: center;
}
nav ul li{
display: table-cell;
min-width: 50px;
border-right: 1px solid #000000;
}
nav ul li:first-child{
border-left: 1px solid #000000;
}
nav ul li a{
display: block;
width: 100%;
padding: 10px 0;
text-decoration: none;
color: #000000;
}
nav ul li a:hover{
background-color:#1b9bff;
border-bottom: 5px solid #1b9bff;
}
nav ul li.current{
font-weight: bold;
}
nav ul li.current a{
border-bottom: 5px solid #1b9bff;
color: #1b9bff;
}
nav ul li.current a:hover{
border-bottom: 5px solid #ffffff;
color: #ffffff;
}
button{
  margin-bottom:10px;
}
.main{
  margin-left:30px;
}
.main1{
  float:left;
}
.main2{
  float:right;
  margin-top:20px;
  margin-right:300px;
}
</style>

app/views/management/new.html.erb
<h1>新規科目の追加</h1>
<%= form_for @management, url: {action: :create} do |f| %>
  <p><%= f.label :subject, '科目名：' %>
  <%= f.text_field :subject %></p>
  <p><%= f.label :annual, '開講年次' %> 
  <%= f.text_field :annual %></p>
  <p><%= f.label :link, 'シラバスリンク' %> 
  <%= f.text_field :link %></p>
  </div>
  <%= f.submit '登録' %>
<% end %>

app/views/top/login.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>
<h1>ログイン</h1>
<%= form_tag top_login_path, method: :post do %>
  <%= label_tag :student_num, '学籍番号' %> 
  <%= text_field_tag :student_num %><br>
  <%= label_tag :pass, 'パスワード' %> 
  <%= password_field_tag :pass %> 
  <%= submit_tag 'ログイン' %>
<% end %>

app/views/user/index.html.erb
<header>
  <nav>
    <ul>
    <li class="current"><%= link_to 'ホーム', root_path %></li>
    <li><%= link_to '新規ユーザ追加', new_user_path %></li>
    <li><% if current_user %>
          <%= link_to 'ログアウト', top_logout_path %>
        <% else %>
          <%= link_to 'ログイン', top_main_path %>
        <% end %></li>
    <li><% if current_user %>
          <%= current_user.student_num.to_s + "さん" %>
        <% else %>
          ゲストさん
        <% end %></li>
    <li id = "setting"><% if current_user %>
              <%= link_to image_tag("setting.png", class: 'setting_img'), management_index_path %>
            <% else %>
              <%= link_to image_tag("setting.png", class: 'setting_img'), '/' %>
            <% end %></li>
    </ul>
  </nav>
</header>

<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>
<div class = "main">
  <div class = content1>
    <% if current_user %>
      <strong><%= link_to '科目情報の閲覧', valuation_indexView_path %></strong>
    <% else %>
      <strong><%= link_to '科目情報の閲覧', top_main_path %></strong>
    <% end %>
  </div>
  <div class = content2>
    <% if current_user %>
      <strong><%= link_to '科目情報の登録', valuation_index_path %></strong>
     <% else %>
      <strong><%= link_to '科目情報の登録', top_main_path %></strong>
    <% end %>
  </div>
</div>
<style>
nav{
border-bottom: 1px solid #000000;
}
nav ul{
display: table;
margin: 0 auto;
padding: 0;
width: 80%;
text-align: center;
}
nav ul li{
display: table-cell;
min-width: 50px;
border-right: 1px solid #000000;
font-weight: bold;
}
nav ul li:first-child{
border-left: 1px solid #000000;
}
nav ul li a{
display: block;
width: 100%;
padding: 10px 0;
text-decoration: none;
color: #000000;
text-decoration: none;
}
nav ul li a:hover{
background-color:#1b9bff;
border-bottom: 5px solid #1b9bff;
color: #ffffff;
text-decoration: none;
}
nav ul li.current{
font-weight: bold;
text-decoration: none;
}
nav ul li.current a{
border-bottom: 5px solid #1b9bff;
color: #1b9bff;
text-decoration: none;
}
nav ul li.current a:hover{
border-bottom: 5px solid #ffffff;
color: #ffffff;
text-decoration: none;
}
.content1{
position: absolute; 
left:300px;
top:300px;
float:left;
width: 300px;
border-radius: 50%;
background-color:#1b9bff;
text-align:center;
line-height: 300px;
font-size:24pt;
}
.content1 a{
  text-decoration: none;
}
.content1 a:link{
  color:#ffffff;
}
.content2{
position: absolute; 
right:300px;
top:300px;
float:right;
width: 300px;
border-radius: 50%;
background-color:#1b9bff;
text-align:center;
line-height: 300px;
font-size:24pt;
}
.content2 a{
  text-decoration: none;
}
.content2 a:link{
  color:#ffffff;
}
.main{
 display: flex;
 width : 100%;
 text-align: center;
}
.main :visited{
  color :#ffffff;
}
.setting_img{
  width:20px;
}
nav ul li #setting a{
  background-color:#ffffff;
}
nav ul li #setting a:hover{
  background-color:#ffffff;
}
</style>

app/views/user/new.html.erb
<div class = "form_block">
<h1>新規登録</h1>
<%= form_for @user, url: {action: :create} do |f| %>
  <%= f.label :student_num, '学籍番号'%> 
  <%= f.text_field :student_num %><br>
  <%= f.label :password, 'パスワード' %> 
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation, 'パスワード（確認）' %> 
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit '登録' %>
<% end %>
</div>

app/views/valuation/index.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>
<!DOCTYPE html>
<html lang="jp" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>情報学科履修一覧（専門科目）</title>
  </head>
  <header>
    <h1>情報学科専門科目講義一覧</h1><br>
  </header>
  <body>
    <%= form_tag({controller:"valuation",action:"index"}, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag "検索" ,:message => nil ,class: "button is-info"%> 
    <button><%= link_to "全表示", valuation_index_path %></button>
    <% end %>
    <br>
    <table border="1">
    <tr>
      <th>　科目名　</th>
      <th>　開講年次　</th>
      <th>　シラバス　</th>
      <th>　コメント評価を登録</th>
    </tr>
    <% @management.each do |e| %>
    <tr>
      <td><%= e.subject %></td>
      <td><%= e.annual %></td>
      <td><%= link_to 'シラバス', e.link, target: :_blank %></td>
      <td><%= link_to '評価登録', new_valuation_path(id: e.id) %></td>
    </tr>
    <% end %>
  </table><br>
  <button><%= link_to '戻る', "/" %></button>
  </body>
</html>

app/views/valuation/indexView.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<!DOCTYPE html>
<html lang="jp" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>情報学科履修一覧（専門科目）</title>
  </head>
  <header>
    <h1>情報学科専門科目講義一覧</h1><br>
  </header>
  <body>
    <%= form_tag({controller:"valuation",action:"index"}, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag "検索" ,:message => nil ,class: "button is-info" %>
    <button><%= link_to "全表示", valuation_indexView_path %></button>
    <% end %>
    <br>
    <table border="1">
    <tr>
      <th>　科目名　</th>
      <th>　開講年次　</th>
      <th>　シラバス　</th>
      <th>　コメント評価を見る　</th>
    </tr>
    <% @management.each do |e| %>
    <tr>
      <td><%= e.subject %></td>
      <td><%= e.annual %></td>
      <td><%= link_to 'シラバス', e.link, target: :_blank %></td>
      <td><%= link_to '評価閲覧', valuationviews_show_path(id: e.id) %></td>
    </tr>
    <% end %>
  </table><br>
  <button><%= link_to '戻る', "/" %></button>
  </body>
</html>

app/views/valuation/new.html.erb
<% if flash[:notice] %>
   <%= flash[:notice] %>
<% end %>

<% if @valuation.errors.present? %>
<h3>エラーがあります</h3>
<ul>
  <% @valuation.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<div class="title">
  <b><%= @management.subject %></b>
</div>
<%= form_for @valuation, url: {action: :create} do |f| %>
<br>
<div class="main">
  <%= f.label :comment, 'コメント　(300字以内)' %><br>
  <%= f.text_area :comment ,:size=>"60x5"%><br><br>
  <%= f.label :star, '評価　(最大100点)' %> <br>
  <%= f.text_field :star %>点<br>
  <%= hidden_field_tag :id, params[:id] %><br>
  <%= f.submit '登録' %>
</div>
<% end %>

<style>
.title{
font-size:24pt;
margin-left:10px;
}
.main{
margin-left:20px;
}
</style>

app/views/valuationviews/show.html.erb
<% if flash[:info] %>
  <%= flash[:info] %>
<% end %>
<div class="title">
  <b><%= @management.subject %></b>


  <b id = "avg">平均値：<%= Valuation.where(subject: params[:id]).average(:star).round(1) %>点<br></b>
</div>




<div class = "button">
  <button><%= link_to '一覧へ戻る', valuation_indexView_path %></button>
</div>

  <% @valuation.each do |e| %>
  <div class = "main">
    <p>
    <b>コメント</b>：<%= e.comment %><br>
    <b>評価</b>：<%= e.star.to_i %>点<br>
    <b>投稿日時</b>：<%= e.tdate.strftime('%Y/%m/%d %H:%M:%S') %>
    </p>
  </div>
<% end %>
<style>
.title{
  font-size:24pt;
  margin-left:10px;
}
.title #avg{
  font-size:20pt;
  padding-left:25px;
}
.main{
  border:solid 3px #1b9bff;
  border-radius: 10px;/*角の丸み*/
  padding:10px 20px;
  margin-top:20px;
  margin-right:60px;
  margin-left:60px;
}
.button{
  margin-left:60px;
}
</style>